## Some vocabulary

* In NumPy, each dimension is called an **axis**.
* The number of axes is called the **rank**.
    * For example, the above 3x4 matrix is an array of rank 2 (it is 2-dimensional).
    * The first axis has length 3, the second has length 4.
* An array's list of axis lengths is called the **shape** of the array.
    * For example, the above matrix's shape is `(3, 4)`.
    * The rank is equal to the shape's length.
* The **size** of an array is the total number of elements, which is the product of all axis lengths (e.g. 3*4=12)

#### Converting Python list to numpy array

In [2]:
import numpy as np
my_list = [1,2,3,4]

arr1 = np.array(my_list)

print(arr1)
print(type(arr1))
print("Rank:" ,arr1.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
Rank: 1


#### Like range() in python we have arange() in numpy

In [3]:
arr2 = np.arange(1,10)

print(arr2)
print(type(arr2))


[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


##### arange() with step

In [4]:
arr3 = np.arange(0,10,2)

print(arr3)

print(arr3[-1]) ## accessing elements by index works

arr2

[0 2 4 6 8]
8


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
c = np.arange(1,5)

print(c.dtype,c)

c = np.arange(1.0,50)

print(c.dtype,c)

int64 [1 2 3 4]
float64 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]


Instead of numpy guessing the dataype we can also explicitly specify the datatype

In [6]:
d = np.arange(1,5,dtype=np.complex64)
print(d.dtype,d)

complex64 [1.+0.j 2.+0.j 3.+0.j 4.+0.j]


Available data types include signed `int8`, `int16`, `int32`, `int64`, unsigned `uint8`|`16`|`32`|`64`, `float16`|`32`|`64` and `complex64`|`128`. Check out the documentation for the [basic types](https://numpy.org/doc/stable/user/basics.types.html) and [sized aliases](https://numpy.org/doc/stable/reference/arrays.scalars.html#sized-aliases) for the full list.

## `itemsize`
The `itemsize` attribute returns the size (in bytes) of each item:

In [7]:
e = np.arange(1,5,dtype=np.complex64)
e.itemsize

8

## `data` buffer
An array's data is actually stored in memory as a flat (one dimensional) byte buffer. It is available *via* the `data` attribute (you will rarely need it, though).

In [8]:
f = np.array([[1,2],[1000,2000]],dtype=np.int32)

print(f)
print(f.data)

[[   1    2]
 [1000 2000]]


##### Creating a 2-dimensional array of zeros or ones( often reffered to as matrix )

In [9]:
arr4 = np.zeros((5,5)) #First number is rows and second is columns

arr4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
arr5 = np.ones((2,3))

arr5

array([[1., 1., 1.],
       [1., 1., 1.]])

##### The decomal point after 0 and 1 indicates these are not integers but floating point numbers

In [11]:
print(arr5[1][1])
print(type(arr5[1][1]))
print(type(arr5[1]))

1.0
<class 'numpy.float64'>
<class 'numpy.ndarray'>


In [12]:
print(type(1.0))
print( type(1.0) == type(arr5[1][1]))

print(isinstance(arr5[1][1] ,float)) ## numpy float is instance of float type
print(issubclass(np.float64,float)) ## numpy float is instance of float type
print(np.float64.__class__)
print(arr5[1][1].__class__)
print(issubclass(np.float64, type))    # False (It is NOT a subclass of type!)
print(np.float64.mro())

<class 'float'>
False
True
True
<class 'type'>
<class 'numpy.float64'>
False
[<class 'numpy.float64'>, <class 'numpy.floating'>, <class 'numpy.inexact'>, <class 'numpy.number'>, <class 'numpy.generic'>, <class 'float'>, <class 'object'>]


In [13]:
isinstance(object,type)

True

#### Create array/matrices from random integers

In [14]:
np.random.randint(10,100) # Returns a random integer between 10 and 100

97

##### If we want array of random integers

In [15]:
np.random.randint(10,100,(5,5)) # uniform distribution - every number between lower and upper limit has same likelihood of being picked

array([[46, 35, 36, 87, 88],
       [45, 32, 98, 74, 89],
       [73, 73, 93, 86, 54],
       [96, 31, 81, 82, 11],
       [49, 72, 55, 52, 15]])

##### Linearly Spaced Array

In [16]:
print(np.linspace(0,10,6))

print(np.linspace(0,10,20))

[ 0.  2.  4.  6.  8. 10.]
[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


##### Generating same random numbers again and again ( useful for testing )

In [17]:
np.random.seed(101)

print(np.random.randint(0,100,10))

print(np.random.randint(0,100,10))

print(np.random.randint(0,100,(5,5)))

[95 11 81 70 63 87 75  9 77 40]
[ 4 63 40 60 92 64  5 12 93 40]
[[49 83  8 29 59]
 [34 44 72 19 10]
 [76 95 87  0 73]
 [ 8 62 36 83 99]
 [28 63  7 10 52]]


##### Math Operations

In [18]:
arr = np.random.randint(0,100,10)

print(arr)

print(arr.max())

print(arr.argmax()) # Index location of max number

print(arr.min())

print(arr.argmin()) # Index location of min number

print(arr.mean())


[56 38 73 52 18 71 15 44  0 12]
73
2
0
8
37.9


##### Reshaping the array

In place

Changing the shape of an ndarray is as simple as setting its shape attribute. However, the array's size must remain the same.

In [19]:
g = np.arange(24)
print(g)
print("Rank:", g.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Rank: 1


In [20]:
g.shape = (6, 4)
print(g)
print("Rank:", g.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Rank: 2


## `reshape`
The `reshape` function returns a new `ndarray` object pointing at the *same* data. This means that modifying one array will also modify the other.

In [21]:
arr2 = arr.reshape(2,5) # Size should be same otherwise error

print(arr2)

arr3 = arr2.reshape(-1)
## Note: You can only use -1 for one dimension in a reshape command. Numpy will auto calculate that dimension
##Flattening an Array.  z f
##If you want to take a multi-dimensional matrix and turn it back into a flat 1D vector, you can pass -1 as the sole argument:
print(arr3)

print(arr3 is arr2 is arr)

original = np.array([1, 2, 3, 4])
view_2d = original.reshape(2, 2)

print(view_2d)
# Change an element in the reshaped view
view_2d[0, 0] = 99

print(original)

print(original is view_2d)

[[56 38 73 52 18]
 [71 15 44  0 12]]
[56 38 73 52 18 71 15 44  0 12]
False
[[1 2]
 [3 4]]
[99  2  3  4]
False


In Python, the is operator checks for Object Identity—meaning it asks: "Are these two variables pointing to the exact same Python object metadata wrapper in memory?" When you reshape a NumPy array, the answer is False because original and view_2d are two completely distinct Python objects. They have different shapes, different strides, and independent tracking attributes.
However, they are considered a "view" because they share the exact same underlying raw data buffer in memory.
The Anatomy of a NumPy Array View
To understand this perfectly, think of a NumPy array as a wrapper made of two distinct parts:
The Metadata Wrapper: A lightweight Python object containing the dimension tuple (shape), data rules (dtype), and stepping instructions (strides).
The Data Buffer: A raw, flat block of C-contiguous memory holding the actual binary numbers.  
Programiz
When you call view_2d = original.reshape(2, 2), NumPy allocates a brand new metadata wrapper object in Python, but it points that new wrapper's data pointer straight to the original array's memory address.
Because the wrapper objects themselves live at different memory addresses, a direct Python identity comparison fails:

## `ravel`
Finally, the `ravel` function returns a new one-dimensional `ndarray` that also points to the same data:

In [22]:
arr2 = arr.ravel()

print(arr2)

print(arr2 is arr)

[56 38 73 52 18 71 15 44  0 12]
False


#### Matrices

In [23]:
mat1 = np.arange(0,125)
mat2 = mat1.reshape(5,5,5)

#print(mat1)
print(mat2)
print(mat2 is mat1)

print(mat2[0][1])

[[[  0   1   2   3   4]
  [  5   6   7   8   9]
  [ 10  11  12  13  14]
  [ 15  16  17  18  19]
  [ 20  21  22  23  24]]

 [[ 25  26  27  28  29]
  [ 30  31  32  33  34]
  [ 35  36  37  38  39]
  [ 40  41  42  43  44]
  [ 45  46  47  48  49]]

 [[ 50  51  52  53  54]
  [ 55  56  57  58  59]
  [ 60  61  62  63  64]
  [ 65  66  67  68  69]
  [ 70  71  72  73  74]]

 [[ 75  76  77  78  79]
  [ 80  81  82  83  84]
  [ 85  86  87  88  89]
  [ 90  91  92  93  94]
  [ 95  96  97  98  99]]

 [[100 101 102 103 104]
  [105 106 107 108 109]
  [110 111 112 113 114]
  [115 116 117 118 119]
  [120 121 122 123 124]]]
False
[5 6 7 8 9]


In [24]:
mat[:2] # First 2 rows

NameError: name 'mat' is not defined

In [ ]:
mat[:,2] # Every Row for second column

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [ ]:
mat[2,:] # Every column value for Row #2

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

##### Comparision of element

In [ ]:
mat >50 # False for all elements where matrix not greater then 50, true for others

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

##### To get the elements with comparision

In [ ]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

#### np.full()

Creates an array of the given shape initialized with a given value.

In [ ]:
np.full((3,4),np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

#### np.empty()

An unitialized array of given size whose contents are not predictable as it is whatever is in memory at that point

In [ ]:
np.empty((2,3))

array([[ 0.,  2.,  4.],
       [ 6.,  8., 10.]])

## `np.random`
A number of functions are available in NumPy's `np.random` module to create `ndarray`s initialized with random values.
You must first create a random number generator (RNG), for example using `np.random.default_rng()`. If you want your program to give reproducible results, you must give the RNG a random seed. The seed can be any integer value, for example 42:

In [ ]:
rng = np.random.default_rng(seed=42)

NameError: name 'np' is not defined

The default RNG is Permuted Congruential Generator (PCG64), which is fast and has good statistical properties (i.e., the pseudo-random numbers it generates really look random). Other RNGs are available, but rarely needed:

In [ ]:
# PCG64DXSM: Improved PCG64 with better randomness but slightly slower
rng_pcg64dxsm = np.random.Generator(np.random.PCG64DXSM())

# MT19937 (Mersenne Twister): Older RNG, very long period, fast but weaker randomness quality
rng_mt19937 = np.random.Generator(np.random.MT19937())

# Philox: Counter-based RNG, good for parallel computations
rng_philox = np.random.Generator(np.random.Philox())

# SFC64 (Small Fast Chaotic): Fastest, small state size, good randomness
rng_sfc64 = np.random.Generator(np.random.SFC64())

Now let's use the RNG's `random()` method to create a 3x4 matrix initialized with random floats between 0 and 1 (uniform distribution):

In [ ]:
rng.random((3,4))

array([[0.77395605, 0.43887844, 0.85859792, 0.69736803],
       [0.09417735, 0.97562235, 0.7611397 , 0.78606431],
       [0.12811363, 0.45038594, 0.37079802, 0.92676499]])

Here's a 3x4 matrix containing random floats sampled from a univariate [normal distribution](https://en.wikipedia.org/wiki/Normal_distribution) (Gaussian distribution) of mean 0 and variance 1:

In [ ]:
rng.standard_normal((3,4))

array([[ 0.0660307 ,  1.12724121,  0.46750934, -0.85929246],
       [ 0.36875078, -0.9588826 ,  0.8784503 , -0.04992591],
       [-0.18486236, -0.68092954,  1.22254134, -0.15452948]])

A 3 X 4 matrix containing random integers from 10 to 19 ( the upper bound is excluded )

In [ ]:
rng.integers(10,20,(3,4))

array([[16, 17, 17, 11],
       [13, 14, 14, 10],
       [15, 11, 17, 16]])

random permutation of integers from 0 to 9:

In [ ]:
rng.permutation(10)

array([5, 0, 9, 8, 6, 7, 1, 2, 3, 4])

#### plotting these random distributions

In [ ]:
import plotly.express as px
import pandas as pd

# 1. Create a clean, labeled DataFrame for both distributions
df_rand = pd.DataFrame({'Values': rng.random(10000), 'Distribution': 'rand'})
df_randn = pd.DataFrame({'Values': rng.standard_normal(10000), 'Distribution': 'randn'})
df = pd.concat([df_rand, df_randn])


# 2. Build the chart using the grouped DataFrame
fig = px.histogram(
    df,
    x='Values',
    color='Distribution',  # This explicitly tells Plotly about 'rand' and 'randn'
    title='Random Distributions',
    nbins=100,
    histnorm='probability density',
    barmode="overlay",
    color_discrete_map={'rand': 'blue', 'randn': 'red'} # This works perfectly now!
)




# 3. Handle axis limits, labels, and center the title
fig.update_layout(
    title_x=0.5,
    xaxis_range=[-2.5, 2.5],
    yaxis=dict(title="Density", range=[0, 1.1]),
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
)


# 4. Make the bars transparent with a solid 1px border
""" fig.update_traces(
    marker_color='rgba(0,0,0,0)',
    marker_line_width=1,
    marker_line_color=None  # Leaving this None forces it to inherit 'blue' and 'red'
) """

# 4. Turn down the fill opacity so they blend beautifully like web vectors
fig.update_traces(opacity=0.40)

fig.show()

NameError: name 'rng' is not defined

#### np.fromfunction

You can also initialize an ndarray using a function

In [ ]:
def my_function(z,y,x):
    return x+10 * y + 100 * z

matrix_3d = np.fromfunction(my_function,(3,3,10))

print(matrix_3d)

[[[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.]
  [ 10.  11.  12.  13.  14.  15.  16.  17.  18.  19.]
  [ 20.  21.  22.  23.  24.  25.  26.  27.  28.  29.]]

 [[100. 101. 102. 103. 104. 105. 106. 107. 108. 109.]
  [110. 111. 112. 113. 114. 115. 116. 117. 118. 119.]
  [120. 121. 122. 123. 124. 125. 126. 127. 128. 129.]]

 [[200. 201. 202. 203. 204. 205. 206. 207. 208. 209.]
  [210. 211. 212. 213. 214. 215. 216. 217. 218. 219.]
  [220. 221. 222. 223. 224. 225. 226. 227. 228. 229.]]]


This code creates a 3-dimensional matrix (array) and populates every single cell using its own grid coordinates.
The magic here is happening inside np.fromfunction(). Instead of using slow nested Python for loops, NumPy automatically generates coordinate indexes and passes them straight into your custom function.
Here is exactly how it breaks down step-by-step:

#### 1. Understanding the Shape: (3, 3, 10)
The second argument (3, 3, 10) tells NumPy to build a 3D block of numbers with:
3 layers deep (z-axis)
3 rows high (y-axis)
10 columns wide (x-axis)
This means your final array will contain a total of 3×3×10=90 elements.


#### 2. How Coordinates are Passed
NumPy loops through every single cell position in this 3D space. For each cell, it takes its structural index coordinate and assigns it to your function's arguments:
z = Current layer index (ranges from 0 to 2)
y = Current row index (ranges from 0 to 2)
x = Current column index (ranges from 0 to 9)

#### 3. The Math Rule: x + 10 * y + 100 * z

Your function calculates a unique value for every cell based on where that cell lives.
Multiplying y by 10 shifts the value by tens for each new row.
Multiplying z by 100 shifts the value by hundreds for each new layer.

Example 1: The very first cell
At the top-left corner of the first layer, the coordinates are: z=0, y=0, x=0

                        Value=0+(10×0)+(100×0)=0

Example 2: Moving along the x-axis
Still on the first layer (z=0) and first row (y=0), but moving to the 5th column (x=4):

                        Value=4+(10×0)+(100×0)=4

Example 3: Moving down a row
On the first layer (z=0), second row (y=1), first column (x=0):

                        Value=0+(10×1)+(100×0)=10

Example 4: Jumping to a deeper layer
On the second layer (z=1), third row (y=2), eighth column (x=7):

                        Value=7+(10×2)+(100×1)=127

                        
What the Output Actually Looks Like
Because it's a 3D array, Python prints it layer by layer (slice by slice along the z-axis). It will output 3 separate 3×10 matrices that look like this:


To find the corresponding x and y values at each z layer, you just have to look at how Python prints a 3D matrix.
When NumPy prints a 3-dimensional array, it lays it out as a sequence of standard 2D grids (matrices). Think of each grid as a floor in a building (z). On each floor, the rows represent y and the columns represent x.

In [ ]:
np.array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],   # <-- Layer 0 (z=0)
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],   # <-- Layer 1 (z=1)
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129]],

       [[200, 201, 202, 203, 204, 205, 206, 207, 208, 209],   # <-- Layer 2 (z=2)
        [210, 211, 212, 213, 214, 215, 216, 217, 218, 219],
        [220, 221, 222, 223, 224, 225, 226, 227, 228, 229]]])

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129]],

       [[200, 201, 202, 203, 204, 205, 206, 207, 208, 209],
        [210, 211, 212, 213, 214, 215, 216, 217, 218, 219],
        [220, 221, 222, 223, 224, 225, 226, 227, 228, 229]]])

In [ ]:
## plotting this
import pandas as pd

# 2. Flatten the 3D grid into a clean coordinates DataFrame
# This gives us explicit columns for X, Y, Z, and the calculated Value

print(matrix_3d.shape)
z_indices, y_indices, x_indices = np.indices(matrix_3d.shape)
print(z_indices)
print(type(z_indices))
print(x_indices.flatten())
df = pd.DataFrame({
    'X_Axis': x_indices.flatten(),
    'Y_Axis': y_indices.flatten(),
    'Z_Axis': z_indices.flatten(),
    'Calculated_Value': matrix_3d.flatten()
})

df

# 3. Plot using Plotly Express 3D Scatter
fig = px.scatter_3d(
    df,
    x='X_Axis',
    y='Y_Axis',
    z='Z_Axis',
    color='Calculated_Value',      # Color of dots changes based on the function result
    size='Calculated_Value',       # Dots grow larger as the value increases
    size_max=18,                   # Limits the maximum size of the spheres
    title="Visualizing np.fromfunction (3D Coordinates Map)",
    color_continuous_scale="Viridis"
)

# 4. Clean up the structural layout view
fig.update_layout(
    title_x=0.5,
    scene=dict(
        xaxis=dict(dtick=1),       # Forces step intervals of 1 on grid axes
        yaxis=dict(dtick=1),
        zaxis=dict(dtick=1)
    )
)

fig.show()
#fig = px.line()

(3, 3, 10)
[[[0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]]

 [[1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]]

 [[2 2 2 2 2 2 2 2 2 2]
  [2 2 2 2 2 2 2 2 2 2]
  [2 2 2 2 2 2 2 2 2 2]]]
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6
 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3
 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9]


# Arithmetic operations
All the usual arithmetic operators (`+`, `-`, `*`, `/`, `//`, `**`, etc.) can be used with `ndarray`s. They apply *elementwise*:

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])


print("a + b = ",a+b)
print("a - b = ",a-b)
print("a / b = ",a/b)
print("a // b = ",a//b)
print("a * b = ",a * b)
print("a ** b = ",a ** b)

a + b =  [ 2  4  6  8 10]
a - b =  [0 0 0 0 0]
a / b =  [1. 1. 1. 1. 1.]
a // b =  [1 1 1 1 1]
a * b =  [ 1  4  9 16 25]
a ** b =  [   1    4   27  256 3125]


Note that the multiplication is *not* a matrix multiplication. We will discuss matrix operations below.

The arrays must have the same shape. If they do not, NumPy will apply the *broadcasting rules*.

# Broadcasting

In general, when NumPy expects arrays of the same shape but finds that this is not the case, it applies the so-called *broadcasting* rules:

## First rule
*If the arrays do not have the same rank, then a 1 will be prepended to the smaller ranking arrays until their ranks match.*

In [ ]:
h1 = np.array([1,2])

h2 = np.array([[3,4],[5,6]])

print(h1.ndim)
print(h2.ndim)
print(h2.shape)
# this happens internally
print(h1.reshape((1,2)))
print(h1.reshape((1,2)).ndim)
print("h1 + h2 = ", h1 + h2 )

1
2
(2, 2)
[[1 2]]
2
h1 + h2 =  [[4 6]
 [6 8]]


## Second rule
*Arrays with a 1 along a particular dimension act as if they had the size of the array with the largest shape along that dimension. The value of the array element is repeated along that dimension.*


Example 1: Stretching a Row Vector Vertically


Imagine you want to add these two arrays:
Array A (Large): Shape (3, 4) → 3 rows, 4 columns.
Array B (Small): Shape (1, 4) → 1 row, 4 columns.

NumPy looks at the row dimension. Array A has 3 rows; Array B has 1 row.
Because Array B has a 1, this second rule activates. Array B acts as if it has 3 rows by repeating its single row 3 times downward:

In [ ]:
h1 = np.array([[1],[2]])
# this will become array([[1,1,1],[2,2,2]])
print(h1.shape)
print(h1.ndim)
h2 = np.array([[1,2,3],[4,5,6]])

print(h2.shape)
print(h2.ndim)

print("h1 + h2 = ", h1 + h2 )

(2, 1)
2
(2, 3)
2
h1 + h2 =  [[2 3 4]
 [6 7 8]]


## Third rule
*After rules 1 & 2, the sizes of all arrays must match.*  

When NumPy checks for compatibility, it pairs up the sizes of the axes starting from the rightmost side. For any given axis, the dimensions are compatible only if:

They are completely equal.
One of them is exactly 1.

If both numbers are greater than 1 and they do not match, NumPy's virtual stretching accordion breaks, and it throws a ValueError: operands could not be broadcast together.

In [ ]:
try:
 print()
 np.array([[33,44,55],[23,45,66]]) + np.array([[23,34],[6,5]])
except ValueError as e:
    print(e)


operands could not be broadcast together with shapes (2,3) (2,2) 


Broadcasting rules are used in many NumPy operations, not just arithmetic operations, as we will see below.
For more details about broadcasting, check out [the documentation](https://numpy.org/doc/stable/user/basics.broadcasting.html).

## Upcasting
When trying to combine arrays with different `dtype`s, NumPy will *upcast* to a type capable of handling all possible values (regardless of what the *actual* values are).

In [ ]:
arr1 = np.arange(1,10,dtype=np.int8)

arr1

arr2 = np.arange(21,30,dtype=np.float64)

#arr3 = arr1 + arr2
#### or

arr3 = arr1 + 2.7

print(arr3)

print(arr3.dtype)



[ 3.7  4.7  5.7  6.7  7.7  8.7  9.7 10.7 11.7]
float64


# Conditional operators

The conditional operators also apply elementwise:

In [ ]:
m1 = np.array([0,1,2,3])

m2 = np.array([4,-5,6,-7])

print(m2>m1)

print(m2<0)

m3 = m2[m2<0]

print(m3)

[ True False  True False]
[False  True False  True]
[-5 -7]


# Mathematical and Statistical Functions

Some functions are simple ndarray methods. For Example


In [ ]:

a = np.array([[1,2,3,4],[5,6,7,8]])

print(a.mean())
print(a.max())
print(a.min())
print(a.sum())
print(a.prod())
print(a.std())
print(a.var())


4.5
8
1
36
40320
2.29128784747792
5.25


These functions accept an optional argument `axis` which lets you ask for the operation to be performed on elements along the given axis. For example:

In [ ]:
arr = np.arange(24).reshape((2,3,4))

arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
arr.sum(axis=0) # sum across matrices

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [ ]:
arr.sum(axis=1) # sum across rows

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

## 1. Understanding the Shape: (2, 3, 4)
When you reshape the 24 consecutive numbers (0 to 23), NumPy builds a 3D array structured as (depth, rows, columns):
Axis 0 (Depth): 2 2D matrices (layers)
Axis 1 (Rows): 3 rows per matrix
Axis 2 (Columns): 4 columns per row
Visually, your array c looks like two stacked sheets of paper:

![alt text](image-5.png)

## 2. How c.sum(axis=0) is Achieved
When you pass axis=0 to the .sum() function, you are telling NumPy to collapse the array along the depth axis.
Think of it as looking down from the top of the stack and pushing Layer 0 down directly into Layer 1. NumPy aligns the elements that share the exact same row and column indices across both layers and adds them together.
The Element-by-Element Math:

Top-left element: c[0,0,0] + c[1,0,0] →0+12=12

Next element: c[0,0,1] + c[1,0,1] →1+13=14

Bottom-right element: c[0,2,3] + c[1,2,3] → 11+23=34

Because you collapsed the 2 layers into 1, Axis 0 is eliminated. The resulting shape drops from (2, 3, 4) to (3, 4).

### A Quick Mental Shortcut: > When summing along an axis in NumPy, that specific axis disappears from the shape tuple, and you sum "through" that dimension.
c.sum(axis=0) collapses the layers, resulting in a (3, 4) array.
c.sum(axis=1) collapses the rows, resulting in a (2, 4) array.
c.sum(axis=2) collapses the columns, resulting in a (2, 3) array.

You can also sum over multiple axes:

In [ ]:
arr.sum(axis=(0,2)) # sum across matrices and columns

array([ 60,  92, 124])

#### Summing Across Axis 0 and Axis 2

Think of this operation as grouping all elements that belong to the same row index across all layers and columns, and adding them all together into a single value.

For Row 0: NumPy takes all numbers in the first row of Layer 0 and the first row of Layer 1, and sums them up:
Row 0 Sum=(0+1+2+3)+(12+13+14+15)=6+54=60

For Row 1: It takes all numbers in the second row of both layers:
Row 1 Sum=(4+5+6+7)+(16+17+18+19)=22+70=92

For Row 2: It takes all numbers in the third row of both layers:
Row 2 Sum=(8+9+10+11)+(20+21+22+23)=38+86=124

## Universal functions
NumPy also provides fast elementwise functions called *universal functions*, or **ufunc**. They are vectorized wrappers of simple functions. For example `square` returns a new `ndarray` which is a copy of the original `ndarray` except that each element is squared:

A ufunc performs element-by-element (vectorized) operations on an array. Instead of writing a slow Python loop to look at each number individually, NumPy applies the mathematical function to every element in a simultaneously.

In [ ]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
np.square(a)

array([[  6.25,   9.61,  49.  ],
       [100.  , 121.  , 144.  ]])

In [ ]:
fig = px.line(x=a.flatten(),y=np.square(a).flatten(),labels={'x': 'a', 'y': 'a squared'})

fig.show()

Here are a few more useful unary ufuncs:

In [ ]:
print("Original ndarray")
print(a)
for func in (np.abs, np.sqrt, np.exp, np.log, np.sign, np.ceil, np.modf, np.isnan, np.cos):
    print("\n", func.__name__)
    print(func(a))

Original ndarray
[[-2.5  3.1  7. ]
 [10.  11.  12. ]]

 absolute
[[ 2.5  3.1  7. ]
 [10.  11.  12. ]]

 sqrt
[[       nan 1.76068169 2.64575131]
 [3.16227766 3.31662479 3.46410162]]

 exp
[[8.20849986e-02 2.21979513e+01 1.09663316e+03]
 [2.20264658e+04 5.98741417e+04 1.62754791e+05]]

 log
[[       nan 1.13140211 1.94591015]
 [2.30258509 2.39789527 2.48490665]]

 sign
[[-1.  1.  1.]
 [ 1.  1.  1.]]

 ceil
[[-2.  4.  7.]
 [10. 11. 12.]]

 modf
(array([[-0.5,  0.1,  0. ],
       [ 0. ,  0. ,  0. ]]), array([[-2.,  3.,  7.],
       [10., 11., 12.]]))

 isnan
[[False False False]
 [False False False]]

 cos
[[-0.80114362 -0.99913515  0.75390225]
 [-0.83907153  0.0044257   0.84385396]]


/var/folders/2x/xz3pfrls6n7bqypm_tf6396w0000gn/T/ipykernel_5722/2634842825.py:5: RuntimeWarning: invalid value encountered in sqrt
  print(func(a))
/var/folders/2x/xz3pfrls6n7bqypm_tf6396w0000gn/T/ipykernel_5722/2634842825.py:5: RuntimeWarning: invalid value encountered in log
  print(func(a))


## 1. np.abs (Absolute Value)
Calculates the absolute (positive) value of each element. It strips away any negative signs.
What it does: Turns negative numbers into positive numbers; leaves positive numbers and zero unchanged.
Example: -1.5 becomes 1.5.

## 2. np.sqrt (Square Root)
Calculates the square root ( x ) of each element.
What it does: Finds the number that, when multiplied by itself, gives the original number.
Note: If your array contains negative numbers, NumPy will return nan (Not a Number) for those elements and throw a runtime warning, because the square root of a negative number is not a real number.

## 3. np.exp (Exponential)
Calculates the exponential of all elements (e^x), where e is Euler's constant (approximately 2.71828).
What it does: Raises e to the power of the element (e
element).

Example: If an element is 0.0, it becomes 1.0 (since e
0
 =1).

## 4. np.log (Natural Logarithm)
Calculates the natural logarithm (ln(x)), which is the inverse of np.exp.
What it does: Finds the power to which e must be raised to equal the element.
Note: If an element is 0, it returns -inf (−∞). If an element is negative, it returns nan.

## 5. np.sign (Sign Indication)
Extracts the sign of each element in the array.
What it does: It returns:
-1 if the number is negative.
0 if the number is zero.
1 if the number is positive.
nan if the element is nan.

## 6. np.ceil (Ceiling)
Rounds each element up to the nearest integer.
What it does: Finds the smallest integer that is greater than or equal to the element. Think of it as rounding "towards positive infinity."
Example: 2.3 rounds up to 3.0. Crucially, -1.5 rounds up to -1.0 (because −1 is larger than −1.5).

## 7. np.modf (Fractional and Integral Parts)
Breaks each element down into its fractional part and its integer part.
What it does: It actually returns two arrays at the same time: the first array contains the fractional parts (the decimals), and the second array contains the integral parts (the whole numbers). Both arrays inherit the sign of the original number.
Example: -1.5 splits into a fractional part of -0.5 and an integral part of -1.0.


## 8. np.isnan (Is Not a Number)
Tests each element to see if it is a NaN (Not a Number) value, which usually represents missing or corrupted data.
What it does: Returns a Boolean array (True or False).
Example: Returns True only where an element is explicitly np.nan; returns False for normal numbers.


## 9. np.cos (Cosine)
Calculates the trigonometric cosine of each element.
What it does: Assumes the numbers in your array are in radians (not degrees) and maps them onto a standard cosine wave, returning values between -1.0 and 1.0.
Example: 0.0 becomes 1.0.

## Binary ufuncs
There are also many binary ufuncs, that apply elementwise on two `ndarray`s.  Broadcasting rules are applied if the arrays do not have the same shape:

In [ ]:
a = np.array([1, -2, 3, 4])
b = np.array([2, 8, -1, 7])
np.add(a, b)  # equivalent to a + b

array([ 3,  6,  2, 11])

In [ ]:
np.greater(a, b)  # equivalent to a > b

array([False, False,  True, False])

In [ ]:
np.maximum(a, b)

array([2, 8, 3, 7])

In [ ]:
np.copysign(a, b)

array([ 1.,  2., -3.,  4.])

# Array indexing
## One-dimensional arrays
One-dimensional NumPy arrays can be accessed more or less like regular python arrays:

In [ ]:
a = np.array([1, 5, 3, 19, 13, 7, 3])
a[3]

np.int64(19)

In [ ]:
a[2:5]

array([ 3, 19, 13])

In [ ]:
a[2:-1]

array([ 3, 19, 13,  7])

In [ ]:
a[:2]

array([1, 5])

In [ ]:
a[2::2]

array([ 3, 13,  3])

In [ ]:
a[::-1]

array([ 3,  7, 13, 19,  3,  5,  1])

In [ ]:
a[3]=999
a

array([  1,   5,   3, 999,  13,   7,   3])

You can also modify an ndarray slice:

In [ ]:
a[2:5] = [997, 998, 999]
a

array([  1,   5, 997, 998, 999,   7,   3])

## Differences with regular python arrays
Contrary to regular python arrays, if you assign a single value to an `ndarray` slice, it is copied across the whole slice, thanks to broadcasting rules discussed above.

In [ ]:
a[2:5] = -1
a

array([ 1,  5, -1, -1, -1,  7,  3])

Also, you cannot grow or shrink ndarrays this way:

In [ ]:
try:
    a[2:5] = [1,2,3,4,5,6]  # too long
except ValueError as e:
    print(e)

could not broadcast input array from shape (6,) into shape (3,)


In [ ]:
try:
    del a[2:5]
except ValueError as e:
    print(e)

cannot delete array elements


On a regular Python list, this code works flawlessly. The del statement mutates the list in place by removing the elements from index 2 up to (but not including) index 5.

NumPy arrays have a fixed size in memory. You cannot dynamically delete elements or change the array's shape in place using the del keyword.

How to actually delete elements in NumPy

If your goal is to delete a slice of a NumPy array, you cannot use del. Instead, you must use the np.delete() function, which creates a new array with those elements removed:

In [ ]:

a = np.array([0, 1, 2, 3, 4, 5, 6])

# np.delete takes the array and a list/range of indices to remove
a = np.delete(a, slice(2, 5))

print(slice(2, 5))
print(a)
# Output: [0, 1, 5, 6]

slice(2, 5, None)
[0 1 5 6]


Last but not least, `ndarray` **slices are actually *views*** on the same data buffer. This means that if you create a slice and modify it, you are actually going to modify the original `ndarray` as well!

In [ ]:
a_slice = a[2:6]
a_slice[1] = 1000
a  # the original array was modified!

array([   0,    1,    5, 1000])

In [ ]:
a[3] = 2000
a_slice  # similarly, modifying the original array modifies the slice!

array([   5, 2000])

If you want a copy of the data, you need to use the `copy` method:

In [ ]:
another_slice = a[2:6].copy()
another_slice[1] = 3000
a  # the original array is untouched

array([   0,    1,    5, 2000])

In [ ]:
a[3] = 4000
another_slice  # similarly, modifying the original array does not affect the slice copy

array([   5, 3000])

## Multidimensional arrays
Multidimensional arrays can be accessed in a similar way by providing an index or slice for each axis, separated by commas:

In [25]:
b = np.arange(48).reshape(4,12)

b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

In [28]:
b[b>11]

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
       46, 47])

In [ ]:
b[1, 2]

np.int64(14)

In [ ]:
b[1, :] # row 1, all columns

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [ ]:
b[:, 1]  # all rows, column 1

array([ 1, 13, 25, 37])

**Caution**: note the subtle difference between these two expressions:

In [ ]:
b[1, :]

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [ ]:
b[1:2, :]

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

The first expression returns row 1 as a 1D array of shape `(12,)`, while the second returns that same row as a 2D array of shape `(1, 12)`.

## Fancy indexing
You may also specify a list of indices that you are interested in. This is referred to as *fancy indexing*.

In [ ]:
b[(0,2), 2:5]  # rows 0 and 2, columns 2 to 4 (5-1)

array([[ 2,  3,  4],
       [26, 27, 28]])

In [ ]:
b[:, (-1, 2, -1)]  # all rows, columns -1 (last), 2 and -1 (again, and in this order)

array([[11,  2, 11],
       [23, 14, 23],
       [35, 26, 35],
       [47, 38, 47]])

If you provide multiple index arrays, you get a 1D `ndarray` containing the values of the elements at the specified coordinates.

In [ ]:
b[(-1, 2, -1, 2), (5, 9, 1, 9)]  # returns a 1D array with b[-1, 5], b[2, 9], b[-1, 1] and b[2, 9] (again)

array([41, 33, 37, 33])

In [ ]:
b[[-1, 2, -1, 2], [5, 9, 1, 9]] 

array([41, 33, 37, 33])

## Higher dimensions
Everything works just as well with higher dimensional arrays, but it's useful to look at a few examples:

In [ ]:
c = b.reshape(4,2,6)
c

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]]])

In [ ]:
c[2, 1, 4]  # matrix 2, row 1, col 4

np.int64(34)

In [ ]:
c[2, :, 3]  # matrix 2, all rows, col 3

array([27, 33])

If you omit coordinates for some axes, then all elements in these axes are returned:

In [ ]:
c[2, 1]  # Return matrix 2, row 1, all columns.  This is equivalent to c[2, 1, :]

array([30, 31, 32, 33, 34, 35])

## Ellipsis (`...`)
You may also write an ellipsis (`...`) to ask that all non-specified axes be entirely included.

In [ ]:
c[2, ...]  #  matrix 2, all rows, all columns.  This is equivalent to c[2, :, :]

array([[24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
c[2, 1, ...]  # matrix 2, row 1, all columns.  This is equivalent to c[2, 1, :]

array([30, 31, 32, 33, 34, 35])

In [ ]:
c[2, ..., 3]  # matrix 2, all rows, column 3.  This is equivalent to c[2, :, 3]

array([27, 33])

In [ ]:
c[..., 3]  # all matrices, all rows, column 3.  This is equivalent to c[:, :, 3]

array([[ 3,  9],
       [15, 21],
       [27, 33],
       [39, 45]])

## Boolean indexing
You can also provide an `ndarray` of boolean values on one axis to specify the indices that you want to access.

In [ ]:
b = np.arange(48).reshape(4, 12)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

In [ ]:
rows_on = np.array([True, False, True, False])
b[rows_on, :]  # Rows 0 and 2, all columns. Equivalent to b[(0, 2), :]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [ ]:
cols_on = np.array([False, True, False] * 4)
b[:, cols_on]  # All rows, columns 1, 4, 7 and 10

array([[ 1,  4,  7, 10],
       [13, 16, 19, 22],
       [25, 28, 31, 34],
       [37, 40, 43, 46]])

## `np.ix_`
You cannot use boolean indexing this way on multiple axes, but you can work around this by using the `ix_` function:

In [ ]:
b[np.ix_(rows_on, cols_on)]

array([[ 1,  4,  7, 10],
       [25, 28, 31, 34]])

In [ ]:
np.ix_(rows_on, cols_on)

(array([[0],
        [2]]),
 array([[ 1,  4,  7, 10]]))

If you use a boolean array that has the same shape as the `ndarray`, then you get in return a 1D array containing all the values that have `True` at their coordinate. This is generally used along with conditional operators:

In [ ]:
b[b % 3 == 1]

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46])